---

- name: install packages
  hosts: localhost
  gather_facts: no
  become: true

  tasks:
    - name: update
      pacman:
        update_cache: yes

    - name: pacman
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - firefox
        - docker
        - python3
        - python-pip
        - git
        - nodejs
        - rust
        - xclip
