---

- name: update
  pacman:
    update_cache: "yes"

- name: pacman
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - firefox
    - docker
    - docker-compose
    - python3
    - python-pip
    - git
    - rust
    - xclip
    - sshpass
    - pass
    - passmenu
    - bash-completion

- name: ensure not installed
  pacman:
    name: "{{ item }}"
    state: absent
  loop:
    - nodejs

- name: bluetooth
  tags: 
    - "bluetooth"
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - bluez
    - bluez-utils
    - blueberry
...
