---

- name: update
  pacman:
    update_cache: "yes"

- name: pacman
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - firefox
    - docker
    - docker-compose
    - python3
    - python-pip
    - git
    - nodejs
    - rust
    - xclip
    - sshpass
