---

- name: cleanup directory
  file:
    state: absent
    path: "/home/bob/{{ item }}"
  loop:
    - Documents
    - Pictures
    - Desktop
    - Music
    - Templates
  tags: archi

- name: create directories
  file:
    state: directory
    path: "/home/bob/{{ item }}"
  loop:
    - ghub
    - .vim
    - .ssh/config
  tags: archi
